---
name: "🐛 Bug Report"
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behavior
      description: |
        Please include full errors, uncaught exceptions, screenshots, and relevant logs.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: |
        Provide steps to reproduce the behavior.
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: |
        What did you expect to happen?
    validations:
      required: false

  - type: input
    id: os-version
    attributes:
      label: Operating system type and version
    validations:
      required: true
